name: PR Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 3
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Set environment variables
      run: |
        echo "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Run code linting
      run: dotnet format --verify-no-changes
      continue-on-error: true
      

    - name: Check code coverage
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Run security scan
      uses: github/codeql-action/init@v1
      with:
        languages: csharp
